version: '3'

services:
  mariadb:
    image: mariadb:10.11
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3306:3306'
    volumes:
      - ./db-init.sql:/docker-entrypoint-initdb.d/db-init.sql
